# Generated by Django 5.0.3 on 2024-10-30 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horcrux', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivariety',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='chaivariety',
            name='pricing',
            field=models.TextField(default=''),
        ),
    ]
