# Generated by Django 5.0.3 on 2024-10-30 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horcrux', '0002_chaivariety_description_chaivariety_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaivariety',
            name='pricing',
            field=models.IntegerField(default=0),
        ),
    ]
